author: mncat77
database: false
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: me.mncat77.slender2go.Slender2Go
name: Slender2Go
startup: postworld
version: '1.5'
commands:
   page:
      description: Allows you to set the location of a page
      usage: /<command> <pagenumber>